### ISSUE TITLE
Fix Ellipse Bounding Box Colors

### ISSUE THREAD

**Issue by James-Oswald** [RAIRLab/Peirce-My-Heart#178]
Unplaced atoms correctly display their bounding box colors.
<img width="50" alt="image" src="https://github.com/RAIRLab/Peirce-My-Heart/assets/43485956/77576530-1ee4-4c55-a1f6-d2b21e305115">
Ellipses display a black box but should display a box the same color as the ellipse.
<img width="95" alt="image" src="https://github.com/RAIRLab/Peirce-My-Heart/assets/43485956/2b8ed7dd-916c-499f-a5f3-7520c80afcbd">
<img width="179" alt="image" src="https://github.com/RAIRLab/Peirce-My-Heart/assets/43485956/c951f71f-6e83-4a4a-ba0f-eea721c3c7d2">

**Comment by DawnTheWitch** [comment]
Ok so I figured this was an easy fix before bed so I decided to just give it a shot. The primary issue is that the drawing of the rectangle has been in create ellipse still. I kind of just left this here because calculating the rectangle for circumscribed ellipses was going to be hell. It obviously cannot stay in the createEllipse function so I've moved it over to the draw ellipse function but the only issue is circumscribed ellipses. it doesn't display the actual box of the circumscribed ellipse but I can *probably* calculate the rectangle based off the values in the ellipse, but my eyes are droopy so that's going to be a mission for tomorrow Dawn since this is pretty important for the milestone I feel.

**Comment by RyanR712** [comment]
As a note, on master right now, if your guidelines are on, the first cut placed actually does have the correct color shown. However, after placing one node, as in either an atom or a cut, the highlight stays black. The highlight is also correct after deleting all cuts and drawing a new cut.

**Comment by DawnTheWitch** [comment]
Fixed in Issue #196
