### ISSUE TITLE
Redrawn Cuts and Atoms

### ISSUE THREAD

**Issue by James-Oswald** [RAIRLab/Peirce-My-Heart#20]
The first cut and and the last cut are only drawn once. All cuts in-between this are drawn multiple times, leading to noticeably thicker lines. 
<img width="198" alt="image" src="https://github.com/James-Oswald/PeirceMyHeart/assets/43485956/5dd7f970-4e8d-471c-930e-b1b14b934227">
They should all be drawn only once.

**Comment by James-Oswald** [comment]
This behavior is also seen on artoms 
<img width="146" alt="image" src="https://github.com/RAIRLab/Peirce-My-Heart/assets/43485956/2a9bc49c-54e0-4730-be13-50b1dcf43f80">

**Comment by DawnTheWitch** [comment]
Update: After some testing with the branch from issue #35, this issue is still here. My current idea is that somewhere along the thought process that for whatever reason, more than one cut or atom is being added to the tree at a time. Because of this when it needs to be redrawn it'll draw all of them.
![image](https://github.com/RAIRLab/Peirce-My-Heart/assets/93628226/d62236b2-129d-48ae-9576-3f4700da63bf)
![image](https://github.com/RAIRLab/Peirce-My-Heart/assets/93628226/4539d0d3-3c41-480b-9e72-1b7ab73bac95)
